/**
 * Pure + client-injected trust logic (slice 4): going-pings, report
 * validation, and the detail-path block filter.
 *
 * Pure decisions are free of React/Supabase so they can be tested without a
 * database or browser (see trust.test.ts, matching the feed.ts / auth.ts
 * convention). The ping round-trip takes the SupabaseClient as a parameter
 * (mocked in tests — same pattern as auth.hasActiveSession); the
 * Supabase-facing wrapper lives in db.ts.
 */
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Comment, CommentWithAuthor } from './types'

/** What a ping toggle should do, decided purely (the caller executes it). */
export type PingDecision = 'noop-host' | 'ping' | 'unping'

/**
 * Client guard (slice 4 AC: "host cannot ping own post"): the host of a
 * post cannot ping their own post — the toggle is a no-op. Otherwise the
 * toggle flips the ping's state.
 */
export function planPing(existingPing: boolean, isHost: boolean): PingDecision {
  if (isHost) return 'noop-host'
  return existingPing ? 'unping' : 'ping'
}

/**
 * The "we're going" ping toggle, executed against the given Supabase client
 * (injected so the upsert→delete round-trip is testable with a mock).
 *
 * Reads the post's host first and enforces the host-cannot-ping-own-post
 * guard client-side (the DB has no such check by design — see migration
 * 0007's comment). Returns the new state: true = going.
 */
export async function togglePingWithClient(
  client: SupabaseClient,
  playdateId: string,
): Promise<boolean> {
  const {
    data: { user },
    error: userError,
  } = await client.auth.getUser()
  if (userError) throw userError
  if (!user) throw new Error('No authenticated user — cannot ping a drop-in.')

  const { data: post, error: postError } = await client
    .from('playdates')
    .select('host_profile_id')
    .eq('id', playdateId)
    .maybeSingle()
  if (postError) throw postError
  // Cast via unknown: without generated DB types, rows are inferred loosely
  // (same pattern as db.listMemberships).
  const hostId = post === null ? null : (post as unknown as { host_profile_id: string }).host_profile_id
  const isHost = hostId !== null && hostId === user.id

  const { data: existing, error: existingError } = await client
    .from('going_pings')
    .select('profile_id')
    .eq('playdate_id', playdateId)
    .eq('profile_id', user.id)
    .maybeSingle()
  if (existingError) throw existingError

  const decision = planPing(existing !== null, isHost)
  if (decision === 'noop-host') return false

  if (decision === 'unping') {
    const { error: deleteError } = await client
      .from('going_pings')
      .delete()
      .eq('playdate_id', playdateId)
      .eq('profile_id', user.id)
    if (deleteError) throw deleteError
    return false
  }
  // 'ping': upsert on the unique pair — a concurrent insert of the same
  // row (23505 on the primary key) already means "going".
  const { error: upsertError } = await client
    .from('going_pings')
    .upsert({ playdate_id: playdateId, profile_id: user.id }, { onConflict: 'playdate_id,profile_id' })
  if (upsertError && upsertError.code !== '23505') throw upsertError
  return true
}

/**
 * Validate a report reason (pinned: required, non-empty after trim).
 * Returns an error message, or null when the reason is acceptable.
 */
export function validateReportReason(reason: string): string | null {
  if (reason.trim().length === 0) {
    return 'Tell us what happened — a reason is required.'
  }
  return null
}

/** The shape the detail-path block check needs (Playdate and its joined variants). */
export interface DetailPost {
  host_profile_id: string
}

/**
 * Detail-path block filter (slice 4): the detail page fetches one playdate
 * directly, so the feed query's .not() DB filter (slice 3) cannot cover it —
 * the check happens after the fetch. A blocked host's post renders the
 * hidden/blocked state, never the content (the same rule filterFeed applies
 * in the feed; defense in depth, not a restructure of the feed filter).
 */
export function isHostBlocked(post: DetailPost, blockedHostIds: ReadonlySet<string>): boolean {
  return blockedHostIds.has(post.host_profile_id)
}

/**
 * The reports INSERT payload (a locally-constructed row — id and created_at
 * are generated by the database, so they are not known client-side).
 */
export interface ReportInsertPayload {
  reporter_profile_id: string
  playdate_id: string | null
  reported_profile_id: string | null
  reason: string
}

/**
 * Issue the reports INSERT, on a plain chain (no .select()/.single()).
 *
 * 42501 regression guard (live REST probe 2026-09-09): a .select() on the
 * insert chain makes Supabase send INSERT ... RETURNING, which makes
 * PostgREST SELECT the new row under RLS — and the reports SELECT policy is
 * moderators-only (pinned in plan.md), so a non-moderator reporter gets
 * 42501. A bare INSERT succeeds (no row is read back; the caller only needs
 * success/failure). The client is injected so a mock can model the live
 * behavior (see trust.test.ts).
 */
export async function issueReportInsert(
  client: SupabaseClient,
  payload: ReportInsertPayload,
): Promise<void> {
  const { error } = await client.from('reports').insert(payload)
  if (error) throw error
}

// ---------------------------------------------------------------------------
// V2 slice 4 (ticket 04): comment permissions — the pure seam.
//
// The detail page decides what it RENDERS from these (the delete button,
// the moderator hide button, visibility); migration 0013's RLS is the WALL
// (a non-privileged action is a silent no-op server-side — the logged
// PostgREST 2xx lesson). planCommentAction-style: a pure decision, the
// caller executes (same discipline as planPing / isHostBlocked).

/**
 * The context a comment action is decided against: the signed-in viewer,
 * the event's host (a host may delete any comment on their own event),
 * and the viewer's moderator flag (the shared profile from useSession —
 * the same source the /mod route guard reads via canModerate).
 */
export interface CommentActionContext {
  /** The signed-in viewer's profile id (= auth user id). */
  viewerId: string
  /**
   * The event's host_profile_id (the host may delete any comment OR reply
   * on it — the per-row delete rule, V3 slice 7, ticket 10).
   */
  hostId: string
  /** The viewer's moderator flag (migration 0008 column). */
  isModerator: boolean
}

/** What the signed-in viewer may do with ONE comment row (decided purely). */
export interface CommentActionPlan {
  /**
   * Delete (hard): the ROW's author, or the event's host — evaluated per
   * row (a reply's delete = the REPLY's author or the host; the parent's
   * author does NOT delete a reply; V3 slice 7, ticket 10).
   */
  canDelete: boolean
  /** Hide (soft, writes hidden_at): moderators only (the /mod model; covers replies, V3 slice 7). */
  canHide: boolean
  /**
   * Visible: hidden_at is null. Hidden comments are invisible to everyone
   * (the SELECT policy filters them DB-side; this is the pure mirror for
   * rows that are somehow in hand).
   */
  canSee: boolean
  /**
   * Reply affordance (V3 slice 7, ticket 10 — the one-level pin): TRUE
   * only for a TOP-LEVEL row (parent_id null — missing pre-0023-apply,
   * the types.ts note), for ANY authenticated viewer: replies are open to
   * all signed-in parents (the 2026-09-09 feedback call — no host/mod
   * gate). A reply NEVER offers a reply (no reply-to-replies).
   */
  canReply: boolean
}

/**
 * The pure comment-permission decision for one comment (ticket 04 AC),
 * extended in V3 slice 7 (ticket 10) with the reply affordance: delete is
 * evaluated PER ROW (a reply's delete = the reply's author or the event's
 * host — the parent's author does NOT delete a reply; the rule keys on the
 * row's own author_profile_id, the 0023 header (d) pin), hide covers
 * replies like comments, and canReply carries the one-level pin.
 */
export function planCommentAction(
  comment: Pick<Comment, 'author_profile_id' | 'hidden_at' | 'parent_id'>,
  ctx: CommentActionContext,
): CommentActionPlan {
  // The ROW's author deletes their own row; the EVENT HOST deletes any row
  // on their own event (both paths are the hard delete — for a reply the
  // "author" is the reply's author, never the parent's).
  const canDelete = comment.author_profile_id === ctx.viewerId || ctx.viewerId === ctx.hostId
  // Pre-0023-apply rows lack parent_id (undefined at runtime — the
  // types.ts note): a missing value behaves as null (top-level), so the
  // affordance is offered (Run C ships before the live apply).
  const canReply = (comment.parent_id ?? null) === null
  return {
    canDelete,
    canHide: ctx.isModerator,
    canSee: comment.hidden_at === null,
    canReply,
  }
}

/** Comment body cap (ticket 04: <= 500 chars; the 0013 CHECK is the backstop). */
export const COMMENT_MAX_LENGTH = 500

/**
 * Validate a comment body (ticket 04 AC: empty rejected client- AND
 * DB-side): non-empty after trim, at most COMMENT_MAX_LENGTH characters
 * (the cap is on the raw body, matching the 0013 CHECK). Returns an error
 * message, or null when the body is acceptable.
 */
export function validateCommentBody(body: string): string | null {
  if (body.trim().length === 0) {
    return 'Write a comment first — it cannot be empty.'
  }
  if (body.length > COMMENT_MAX_LENGTH) {
    return `Keep comments to ${COMMENT_MAX_LENGTH} characters.`
  }
  return null
}

// ---------------------------------------------------------------------------
// V2 slice 5 (ticket 05, share + public event view): the pure seam.

/**
 * The share URL for a drop-in (ticket 05): `${baseUrl}/playdate/<id>` when
 * baseUrl (VITE_PUBLIC_BASE_URL) is set — deployment, DECISION 3 —
 * otherwise the window origin (placeholder-safe before deployment: the
 * dev/preview origin is the fallback). Pure so it is unit-testable.
 */
export function buildShareUrl(playdateId: string, baseUrl: string, origin: string): string {
  const base = baseUrl.trim()
  return `${base !== '' ? base : origin}/playdate/${playdateId}`
}

/**
 * Session-storage key for the signed-out "I'm coming" return target
 * (ticket 05 decision 4): the detail path stored BEFORE the /login hop;
 * the app shell applies it only once the onboarding gate has settled.
 */
export const PLAYDATE_RETURN_KEY = 'playdate-return-target'

/**
 * Session-storage key for the ping intent (ticket 05 decision 4, the
 * zero-pressure soul): the playdate id whose ping the returned visitor
 * must EXPLICITLY confirm (the highlighted "Tap to confirm" button) —
 * never a silent auto-ping.
 */
export const PLAYDATE_PING_INTENT_KEY = 'playdate-ping-intent'

/**
 * Whether a stored value is a valid playdate return target (the shell
 * applies ONLY these — a tampered or stale value is ignored, never
 * navigated to): exactly `/playdate/<id>` (a single non-empty segment).
 */
export function isPlaydateReturnTarget(stored: string | null): boolean {
  if (stored === null) return false
  const rest = stored.slice('/playdate/'.length)
  return stored.startsWith('/playdate/') && rest.length > 0 && !rest.includes('/')
}

/**
 * V8 ticket 05 (post edit): the host-only edit path, `/playdate/:id/edit`.
 *
 * `playdateDetailPathFromEditPath` is the target a visitor who may NOT edit
 * is sent to — the post's own detail path, the surface they are already
 * allowed to see (the signed-out public view included). Exactly one
 * non-empty id segment, the `isPublicDetailPath` shape, so a tampered path
 * never resolves to anything but null.
 */
export function playdateDetailPathFromEditPath(pathname: string): string | null {
  const match = /^\/playdate\/([^/]+)\/edit\/?$/.exec(pathname)
  return match === null ? null : `/playdate/${match[1]}`
}

// ---------------------------------------------------------------------------
// V3 slice 7 (ticket 10): one-level comment replies — the pure seam.
//
// Migration 0023 (comments.parent_id + the reply-visibility RLS) is the
// DB-side half; the detail page renders the thread from these — the same
// discipline as planCommentAction / filterFeed: a pure decision over the
// row set, the caller executes the render.

/**
 * One render group of the detail-page comment thread (V3 slice 7, ticket
 * 10, migration 0023): a top-level comment + its one-level replies. The
 * detail page renders `parent` with `children` indented under it (ml-8,
 * 24px avatar); a hidden parent keeps its group with EMPTY children — the
 * moderator's hide covers the thread (the muted parent row itself still
 * renders as today's hidden-top-level chip, its replies don't; 0023
 * header (b)). Pre-0023-apply every group's children is empty (the flat
 * thread renders unchanged — Run C ships before the live apply).
 */
export interface CommentThreadGroup {
  /** The group's top-level comment (it renders muted when hidden). */
  parent: CommentWithAuthor
  /** Replies to the parent, created_at ascending; empty when the parent is
   * hidden (the hidden-parent exclusion) or no reply exists. */
  children: CommentWithAuthor[]
}

/** created_at ascending; stable, so equal timestamps keep the input order. */
function byCreatedAt(a: { created_at: string }, b: { created_at: string }): number {
  return Date.parse(a.created_at) - Date.parse(b.created_at)
}

/**
 * The thread's render groups (V3 slice 7, ticket 10): the flat
 * per-playdate comment list that db.listComments returns (top-level
 * comments + replies, created_at ascending — 0023 reuses the existing
 * (playdate_id, created_at) index scan, 0023 header (e)) in, one
 * CommentThreadGroup per top-level comment out. Pinned semantics:
 *
 * - ORDER: groups by the parent's created_at ascending; children by
 *   created_at ascending (sorted internally, so the output contract holds
 *   even if the input order ever stops being canonical; the sort is
 *   stable, so equal timestamps keep the input order).
 * - HIDDEN-PARENT EXCLUSION (0023 header (b)): when a parent is hidden
 *   (hidden_at !== null), its replies are EXCLUDED from the output — the
 *   group renders the muted parent row only, children empty (the
 *   moderator's hide covers the thread; non-moderators never receive a
 *   hidden parent from the DB, so this branch is the mod view + defense
 *   in depth).
 * - A HIDDEN REPLY itself (hidden_at set, parent visible) stays in its
 *   group (the UI renders the muted chip — same as today's hidden
 *   top-level).
 * - ORPHAN DEFENSE: a reply whose parent_id is not present in the input
 *   list is DROPPED (it forms no group and never renders). Post-apply the
 *   DB makes this a no-op — the parent FK's ON DELETE CASCADE + 0023's
 *   reply-visibility RLS — so this is pure defense in depth against a
 *   malformed row set. A reply pointing at another reply (allowed by the
 *   DB, 0023 header (a) — the one-level pin is client-side) answers a
 *   child, never a group, so it is dropped too: there is no second indent
 *   level.
 * - PRE-APPLY (the types.ts note): before the live 0023 apply, rows lack
 *   parent_id entirely (undefined at runtime) — a missing value behaves
 *   as null, i.e. every row is top-level and every group's children empty:
 *   the CURRENT flat thread renders correctly with no replies present.
 *
 * Empty input → empty output.
 */
export function groupCommentsForRender(
  comments: ReadonlyArray<CommentWithAuthor>,
): CommentThreadGroup[] {
  const byId = new Map<string, CommentWithAuthor>()
  for (const comment of comments) byId.set(comment.id, comment)

  const parents: CommentWithAuthor[] = []
  const repliesByParentId = new Map<string, CommentWithAuthor[]>()
  for (const comment of comments) {
    // Pre-0023-apply rows lack parent_id (undefined at runtime — the
    // types.ts note): a missing value behaves as null (top-level).
    const parentId = comment.parent_id ?? null
    if (parentId === null) {
      parents.push(comment)
      continue
    }
    // Orphan defense (see the doc above): the parent must be in this
    // thread's row set, otherwise the reply is dropped. (A reply pointing
    // at another reply also lands here harmlessly: a reply is never a
    // group, so it can never surface — the one-level pin.)
    if (!byId.has(parentId)) continue
    const siblings = repliesByParentId.get(parentId)
    if (siblings === undefined) {
      repliesByParentId.set(parentId, [comment])
    } else {
      siblings.push(comment)
    }
  }

  parents.sort(byCreatedAt)
  const groups: CommentThreadGroup[] = []
  for (const parent of parents) {
    // Hidden-parent exclusion (0023 header (b)): the mod's hide covers the
    // thread — the muted parent row stays, its replies don't render.
    const children =
      parent.hidden_at !== null
        ? []
        : (repliesByParentId.get(parent.id) ?? []).slice().sort(byCreatedAt)
    groups.push({ parent, children })
  }
  return groups
}
