#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# The project ref is derived, never hardcoded — it comes out of VITE_SUPABASE_URL
# in .env, so this wizard follows the repo instead of pinning a project.
_SUPABASE_URL=$(_existing VITE_SUPABASE_URL || true)
PROJECT_REF=$(printf '%s' "$_SUPABASE_URL" | sed -E 's#https?://([^.]+)\..*#\1#')

banner "Drop In — auth email over Gmail SMTP"

say "Why this exists: Supabase's built-in sender is capped at 2 emails per hour"
say "for the WHOLE project, so password reset is a dead end for a cohort."
printf '\n'
say "This routes Supabase Auth through a Gmail account instead. It costs nothing"
say "and needs no domain — Google wants an app password, not DNS records."
printf '\n'
note "Plan reference: .scratch/ios-notification-hole/plan.md (slice 5)"
note "Ops + verification: docs/email-fallback-ops.md"

if [[ -z "$PROJECT_REF" ]]; then
  warn "Could not read VITE_SUPABASE_URL from $ENV_FILE — dashboard links below will be generic."
  PROJECT_REF="<your-project-ref>"
else
  note "Supabase project ref: $PROJECT_REF"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Google: turn on 2-Step Verification"
say "App passwords do not exist until 2FA is on. This is the step people skip and"
say "then cannot find the App passwords page at all."
printf '\n'
open_url "https://myaccount.google.com/security"
step "Under 'How you sign in to Google', open '2-Step Verification' and turn it on."
step "Finish the phone prompt."
pause "Press Enter once 2FA is ON."

# ──────────────────────────────────────────────────────────────────────────
stage "Google: create an app password"
say "An app password is a 16-character throwaway credential for one app. It is NOT"
say "your Google password, and revoking it later does not touch your account."
printf '\n'
warn "Google shows this password ONCE. If you lose it, just make another."
printf '\n'
open_url "https://myaccount.google.com/apppasswords"
step "Name it 'Drop In'."
step "Click Create. Google shows 16 characters, usually as four space-separated"
step "  groups like 'abcd efgh ijkl mnop'."
step "Copy it and paste it below — spaces are fine, they get stripped."
printf '\n'
ask GMAIL_SENDER_ADDRESS "The Gmail address you will send from (e.g. you@gmail.com):"
ask_secret GMAIL_APP_PASSWORD "Paste the 16-character app password (hidden):"
# Google displays it space-separated; SMTP rejects whitespace. Strip it all.
GMAIL_APP_PASSWORD="$(printf '%s' "${GMAIL_APP_PASSWORD:-}" | tr -d '[:space:]')"
note "Stored ${#GMAIL_APP_PASSWORD} characters after stripping spaces (expect 16)."
if [ "${#GMAIL_APP_PASSWORD}" -ne 16 ]; then
  warn "Not 16 characters. Google app passwords are exactly 16 — re-run this stage if you mis-copied."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: point Auth at Gmail"
say "Google's published SMTP settings. Nothing here is secret except the password."
printf '\n'
note "Host:      smtp.gmail.com"
note "Port:      465   (SSL)  — 587 also works"
note "Username:  ${GMAIL_SENDER_ADDRESS}"
note "Password:  the 16-character app password from stage 2"
printf '\n'
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/smtp"
step "Find Authentication → Emails (the panel may read 'SMTP Settings')."
step "Turn ON 'Enable Custom SMTP'."
step "Host: smtp.gmail.com    Port: 465"
step "Username: your full Gmail address (it must match the sender)"
step "Password: the app password, no spaces"
step "Sender email: ${GMAIL_SENDER_ADDRESS}"
step "Sender name: Drop In"
step "Click Save."
pause "Press Enter once the SMTP settings are saved."

# ──────────────────────────────────────────────────────────────────────────
stage "Supabase: raise the email rate limit"
say "This is the actual bug. The default is 2 per hour for the WHOLE project, so"
say "the third parent to forget a password in an hour gets a hard failure."
printf '\n'
note "This only makes sense now that a real sender is connected — which is why"
note "docs/beta-checklist.md sequences the SMTP change BEFORE this one."
printf '\n'
open_url "https://supabase.com/dashboard/project/${PROJECT_REF}/auth/rate-limits"
step "Find Authentication → Rate Limits."
step "Raise 'Rate limit for sending emails' to 30 per hour."
step "Click Save."
printf '\n'
warn "30/hour is a deliberate beta ceiling, not a measured safe maximum. Gmail"
warn "also imposes daily sending limits, and Google does not publish one number"
warn "for every account type. Check your own before inviting a large cohort."
pause "Press Enter once the rate limit is saved."

# ──────────────────────────────────────────────────────────────────────────
stage "Prove it: a real password reset, in a real inbox"
say "Nothing above is proven until an email actually lands. This is the one check"
say "no amount of local testing can replace."
printf '\n'
open_url "https://drop-in-mu.vercel.app/login"
step "Click 'Forgot password' and enter YOUR OWN email address."
step "Watch the inbox (and the spam folder) for the reset mail."
step "Open the link and confirm it lands on the reset screen."
printf '\n'
if confirm "Did the email arrive and did the link work?"; then
  note "Auth email is live. That was the 2-per-hour wall coming down."
else
  warn "Not delivered. Check, in this order:"
  note "  1. Supabase → Authentication → Logs: did it even attempt a send?"
  note "  2. A 535/auth error there almost always means the app password still"
  note "     has spaces, or 2FA is not really on, or the username is not the"
  note "     full Gmail address."
  note "  3. Gmail → Sent: if it went out, this is deliverability, and the mail"
  note "     is probably in spam. Mark it not-spam once and it learns."
  note "  4. Google Advanced Protection DISABLES app passwords entirely. If that"
  note "     is on for this account, this route cannot work — use another account."
  SKIPPED+=("Password-reset delivery is UNVERIFIED — fix and re-run stage 5")
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Record the values locally"
say "These go into .env for local work. .env is mode 0600 and gitignored. Worth"
say "capturing because Google will never show the app password again."
printf '\n'
write_env GMAIL_SENDER_ADDRESS "$GMAIL_SENDER_ADDRESS"
write_env GMAIL_APP_PASSWORD "$GMAIL_APP_PASSWORD"
printf '\n'
note "No GitHub secrets changed: CI only references vars.VITE_SUPABASE_URL and"
note "vars.VITE_SUPABASE_ANON_KEY, and neither changes here."
printf '\n'
warn "STILL OPEN — this wizard fixes AUTH email only (password reset + invites)."
printf '\n'
say "The playdate NOTIFICATION email (someone joined your drop-in, it was"
say "cancelled, it starts soon) is sent by the send-push Edge Function, which"
say "speaks the Resend HTTP API and reads RESEND_API_KEY / EMAIL_FROM. Gmail SMTP"
say "does NOT switch that on, so the fallback still delivers nothing today."
printf '\n'
note "Options, cheapest first:"
note "  a. Gmail SMTP from the Edge Function too — no domain, but needs a new"
note "     Deno SMTP sender, and leans on a personal mailbox for app traffic."
note "  b. A domain (~\$12/yr) + Resend — durable, and lets the app move off"
note "     drop-in-mu.vercel.app."
note "  c. Defer. The in-app 'While you were away' card already collects every"
note "     notification and needs no email at all."
printf '\n'
note "Verification commands and the full state: docs/email-fallback-ops.md"

finish
