-- ===========================================================================
-- V35-C (migration 0069): a DELIBERATE REVERSAL of migration 0066.
-- ===========================================================================
--
-- Founder ruling (V35-C): the browse/search radius default becomes FIVE MILES.
-- Migration 0066 narrowed `profiles.radius_miles` DEFAULT from 5 to 1; this
-- migration moves it back to 5, undoing that narrowing on purpose.
--
-- What this does: ONE thing — it moves the `profiles.radius_miles` column
-- DEFAULT from 1 back to 5. No column is added or dropped, no existing row's
-- data is touched, no constraint is re-validated, no policy changes. This is
-- a LIVE-DATABASE migration (the project it applies to holds real family
-- data), so it is strictly additive and re-paste-safe.
--
-- THE AGREEMENT THIS FILE MUST KEEP. Two bounds pairs exist and both must
-- agree with the code:
--   * this DEFAULT (5) must agree with `DEFAULT_RADIUS_MILES` in
--     `src/lib/feed.ts` — the app's fallback when a profile row stores nothing.
--     If the two disagree, a fresh row and a missing row mean different things.
--   * the CHECK `profiles_radius_miles_chk` (1–35, migration 0045:65) must
--     agree with `RADIUS_MIN_MILES` / `RADIUS_MAX_MILES` (`src/lib/feed.ts`).
-- THIS MIGRATION DOES NOT TOUCH THE CHECK. 5 is already legal inside 1–35, so
-- there is no constraint change, no re-validation, and no table scan under a
-- share lock — an `alter column … set default` rewrites no rows.
--
-- NO DATA-LOSS EXCEPTION IS NEEDED (rule.json's data-loss rule): nothing is
-- dropped, renamed, or rewritten — `set default` affects only rows inserted
-- AFTER this statement.
--
-- An `alter column … set default` is inherently re-runnable and converges:
-- the second application sets the same value. There is deliberately no `do $$`
-- guard, because a guard is one more thing that can itself drift from the
-- statement it wraps.
-- ===========================================================================

alter table public.profiles alter column radius_miles set default 5;