import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 390, height: 844 } })
await p.goto('http://localhost:4173/browse', { waitUntil: 'networkidle', timeout: 60000 })
await p.waitForTimeout(3000)
console.log('url     :', p.url())
console.log('title   :', await p.title())
console.log('h1/h2   :', await p.locator('h1,h2').allTextContents())
console.log('place-row count:', await p.locator('[data-testid="place-row"]').count())
console.log('any data-photo :', await p.locator('[data-photo]').count())
console.log('see-all present:', await p.locator('[data-testid="places-see-all"]').count())
const body = (await p.locator('body').innerText()).slice(0, 600)
console.log('--- body text ---'); console.log(body)
await b.close()
