import { chromium } from '@playwright/test'
const b = await chromium.launch()
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, storageState: 'e2e/.auth/marker-state.json' })
const p = await ctx.newPage()
await p.goto('http://localhost:4173/browse', { waitUntil: 'networkidle', timeout: 60000 })
await p.waitForTimeout(2500)
await p.locator('[data-testid="places-see-all"]').first().click()
await p.waitForTimeout(1500)
// scroll the real photo into view so lazy loading fires
const img = p.locator('[data-photo="real"]').first()
await img.scrollIntoViewIfNeeded()
await p.waitForTimeout(4000)
const info = await img.evaluate(el => ({ complete: el.complete, nw: el.naturalWidth, nh: el.naturalHeight }))
console.log('after scroll into view:', JSON.stringify(info))
console.log(info.nw > 0 ? 'PASS: the Commons image really loads in the browser' : 'FAIL: image did not load')
await p.screenshot({ path: '.scratch/v18/evidence/probe-photo-card.png' })
await b.close()
